id: url_enrichment_-_generic
version: -1
name: URL Enrichment - Generic
fromversion: 3.6.0
description: |-
  Enrich URL using one or more integrations.

  URL enrichment includes:
  * Verify URL SSL
  * Threat information
  * URL reputaiton
  * Take URL screenshot
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 8ec1d86f-9108-44d5-8c64-49fa9294f043
    type: start
    task:
      id: 8ec1d86f-9108-44d5-8c64-49fa9294f043
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": -39
        }
      }
    note: false
    timertriggers: []
  "16":
    id: "16"
    taskid: 7bc8f493-84d1-4d5e-8bfc-64db0cab685c
    type: condition
    task:
      id: 7bc8f493-84d1-4d5e-8bfc-64db0cab685c
      version: -1
      name: Do we have URLs?
      description: do we have a url to check
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
      - "31"
    scriptarguments:
      value:
        simple: inputs.url
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.URL
            iscontext: true
    view: |-
      {
        "position": {
          "x": 490,
          "y": 125
        }
      }
    note: false
    timertriggers: []
  "24":
    id: "24"
    taskid: 86cea036-b5bf-40d7-86f9-278a0e1d5557
    type: title
    task:
      id: 86cea036-b5bf-40d7-86f9-278a0e1d5557
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1085
        }
      }
    note: false
    timertriggers: []
  "25":
    id: "25"
    taskid: b5ea6e49-a7eb-49d7-8398-3087829d7aee
    type: condition
    task:
      id: b5ea6e49-a7eb-49d7-8398-3087829d7aee
      version: -1
      name: 'Is Rasterize integration enabled? '
      description: Check if we can use rasterize
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "26"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: Rasterize
          - - operator: isEqualString
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 150,
          "y": 640
        }
      }
    note: false
    timertriggers: []
  "26":
    id: "26"
    taskid: 16f823c3-bd44-4fa9-879c-385ac3a21582
    type: regular
    task:
      id: 16f823c3-bd44-4fa9-879c-385ac3a21582
      version: -1
      name: Get URL screenshot
      description: Get the screenshot of the url page
      script: Rasterize|||rasterize
      type: regular
      iscommand: true
      brand: Rasterize
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      height: {}
      type: {}
      url:
        complex:
          root: inputs.URL
          transformers:
          - operator: uniq
      width: {}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 150,
          "y": 870
        }
      }
    note: false
    timertriggers: []
  "27":
    id: "27"
    taskid: 330afbd3-d094-436b-8ebf-8c2fac84563e
    type: condition
    task:
      id: 330afbd3-d094-436b-8ebf-8c2fac84563e
      version: -1
      name: Should the system take URL screenshots?
      description: Checks if the playbook's Rasterize input is equal to "True", to
        determine whether "screenshots" of the URLs should be created.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "25"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.Rasterize
            iscontext: true
          right:
            value:
              simple: "True"
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 150,
          "y": 440
        }
      }
    note: false
    timertriggers: []
  "29":
    id: "29"
    taskid: bf3d5a2f-6be9-4625-80df-e679e2e3e8ef
    type: title
    task:
      id: bf3d5a2f-6be9-4625-80df-e679e2e3e8ef
      version: -1
      name: URL Screenshots
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 150,
          "y": 300
        }
      }
    note: false
    timertriggers: []
  "31":
    id: "31"
    taskid: 35491163-4370-45fb-87d1-5de849f33eb0
    type: title
    task:
      id: 35491163-4370-45fb-87d1-5de849f33eb0
      version: -1
      name: URL Verification
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "33"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 809.5,
          "y": 300
        }
      }
    note: false
    timertriggers: []
  "32":
    id: "32"
    taskid: d7286e0e-1e4b-4c25-86cd-91dbaed4fb0b
    type: regular
    task:
      id: d7286e0e-1e4b-4c25-86cd-91dbaed4fb0b
      version: -1
      name: URL SSL Verification
      description: Verify URL SSL certificate
      scriptName: URLSSLVerification
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      url:
        complex:
          root: inputs.URL
          transformers:
          - operator: uniq
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 809.5,
          "y": 640
        }
      }
    note: false
    timertriggers: []
  "33":
    id: "33"
    taskid: 0c413073-f2af-4cc3-833e-abc0b1fae841
    type: condition
    task:
      id: 0c413073-f2af-4cc3-833e-abc0b1fae841
      version: -1
      name: Should the system verify URLs?
      description: Checks if the playbook's VerifyURL input is equal to "True", to
        determine whether SSL verification should be done on URLs.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "32"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.VerifyURL
            iscontext: true
          right:
            value:
              simple: "True"
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 809.5,
          "y": 440
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.13,
      "16_31_yes": 0.84,
      "25_24_#default#": 0.68,
      "25_26_yes": 0.47,
      "27_24_#default#": 0.47,
      "27_25_yes": 0.5,
      "33_24_#default#": 0.47,
      "33_32_yes": 0.67
    },
    "paper": {
      "dimensions": {
        "height": 1189,
        "width": 1039.5,
        "x": 150,
        "y": -39
      }
    }
  }
inputs:
- key: URL
  value:
    complex:
      root: URL
      accessor: Data
      transformers:
      - operator: uniq
  required: false
  description: URLs to enrich.
- key: Rasterize
  value:
    simple: "True"
  required: false
  description: Should the system take safe screenshots of input URLs?
- key: VerifyURL
  value:
    simple: "True"
  required: false
  description: Should the system verify the input URLs?
outputs:
- contextPath: URL
  description: The URL's object
  type: uknown
- contextPath: URL.Data
  description: The enriched URL
  type: string
- contextPath: DBotScore
  description: The DBotScore
  type: unknown
- contextPath: URL.Malicious
  description: whether url was detected as malicious
  type: unknown
- contextPath: URL.Vendor
  description: name of vendor who labeled as malicious
  type: string
- contextPath: URL.Description
  description: additional info on the url
  type: string
releaseNotes: "Simplification, improved uniqueness of indicators, removal of redundant reputation calculations, changing to meet new conventions"
tests:
  - url_enrichment_-_generic_test